config/routes.rb
ThingsToApples::Application.routes.draw do
  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: [:new, :create],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration
  end
  
  unauthenticated do
    root to: 'home#index'
  end
  get 'play' => 'home#play'
  get 'instructions' => 'home#instructions'
  get 'leaders' => 'home#leaders'
  get 'archives' => 'home#archives'

  authenticated :user do
    root to: 'home#play', as: :auth_root
  end

  resources :games, only: [:new, :create, :show] do
    post :join
    post :respond
    post :score
  end

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :instructions]

  def index
  end
  
  def play
    unless current_user.games.active.count == 0
      redirect_to(game_path(current_user.games.active.first))
    end
  end

  def leaders
  end

  def archives
  end

  def instructions
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/archives.html.haml
%div.row
  %div.span8
    %h3 Archived Games
    %table.table.table-bordered.table-condensed
      %tr
        %th.span2 Rounds
        %th.span2 Players
        %th.span2 Winner(s)
        %th.span2
      - Game.complete.order(created_at: :desc).each do |game|
        %tr
          %td.span2= "#{game.num_rounds}"
          %td.span2= "#{game.num_players}"
          %td.span2= "#{game.winners.map{|winner| winner.email}.to_sentence}"
          %td.span2= link_to('View Details', game_path(game), {class: 'btn'})

app/views/home/dashboard.html.haml
%h3= "#{current_user.email}'s Dashboard"
%hr
= link_to('New Game', new_game_path)
%h4 Games In Progress
%table
  %tr
    %th Game ID
    %th Current / Total Players
    %th Current / Total Rounds
  - current_user.games.in_progress.each do |game|
    %tr
      %td= game.id
      %td= "#{game.players.count} / #{game.num_players}"
      %td= "#{game.round} / #{game.num_rounds}"
%hr
%h4 Games Awaiting Players
%table
  %tr
    %th Game ID
    %th Current / Total Players
    %th Current / Total Rounds
  - Game.awaiting_players.each do |game|
    %tr
      %td= game.id
      %td= "#{game.players.count} / #{game.num_players}"
      %td= "#{game.round} / #{game.num_rounds}"
%hr
%hr
%hr
%h4 Created Games
%table
  %tr
    %th Game ID
    %th Current / Total Players
    %th Current / Total Rounds
  - Game.created_by(current_user).each do |game|
    %tr
      %td= game.id
      %td= "#{game.players.count} / #{game.num_players}"
      %td= "#{game.round} / #{game.num_rounds}"

app/views/home/index.html.haml
%h3 Welcome to Things to Apples
%h4
  = link_to('Login', new_user_session_path)
  or
  = link_to('Sign Up', new_user_registration_path)
  to play.

app/views/home/instructions.html.haml
%h4 Instructions
%ul
  %li Things to Apples is played with 3 or more players for a number of rounds at least as large as the number of players (giving each player an opportunity to be the judge).
  %li A game begins when the required number of players have joined it.
  %li Players are ordered randomly at the start of the game and take turns as the judge in this order.
  %li Each game has a pre-set timeout value.  This is the time that must pass before a disconnected player forfeits his or her turn.  If that player is not the judge then his or her response is forfeited and therefore no points can be awarded.  If that player is the judge, each response is awarded 1 point and the round is over.  
  %li To start a new game...
  %ul
    %li On the ‘Play’ tab click the link the start a new game.
    %li Enter the desired number of players
    %li Enter the desired number of rounds
    %li Enter the desired timeout in minutes
  %li To join a game...
  %ul
    %li On the ‘Play’ tab click the 'Join' button next to a game waiting for players.
  %li To play a round...
  %ul
    %li A card is selected randomly and displayed to all players.
    %li Each player except for the judge responds with a response they fill will garner the most points from the judge.
    %li The judge awards the available points (the number of players in the game) to the responses.

app/views/home/leaders.html.haml
%div.row
  %div.span6
    %h3 Leaderboard
    %table.table.table-bordered.table-condensed
      %tr
        %th.span3 Player
        %th.span1 Wins
        %th.span1 Ties
        %th.span1 Loses
      - User.all.sort_by{|user| [-user.result_sum]}.each do |user|
        %tr
          %td.span3= user.email
          %td.span1= user.wins
          %td.span1= user.ties
          %td.span1= user.loses

app/views/home/play.html.haml
%div.row
  %div.span8
    %div.waiting
      - if Game.waiting_for_players.count > 0
        %h4
          Join an Existing Game
        %table.table.table-bordered.table-condensed
          %tr
            %th.span2 Rounds
            %th.span2 Players
            %th.span2
          - Game.waiting_for_players.each do |game|
            %tr
              %td.span2= "#{game.num_rounds}"
              %td.span2= "#{game.players.count} of #{game.num_players}"
              %td.span2
                = form_for(game, {url: game_join_path(game), method: :post}) do |f|
                  = f.submit('Join')
      - else
        There are no games waiting for players.
    %h4= link_to('Click here to start a new game.', new_game_path)