config/routes.rb
ThingsToApples::Application.routes.draw do
  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: [:new, :create],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration
  end
  
  unauthenticated do
    root to: 'home#index'
  end
  get 'play' => 'home#play'
  get 'instructions' => 'home#instructions'
  get 'leaders' => 'home#leaders'
  get 'archives' => 'home#archives'

  authenticated :user do
    root to: 'home#play', as: :auth_root
  end

  resources :games, only: [:new, :create, :show] do
    post :join
    post :respond
    post :score
  end

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  
  # Associations
  belongs_to :creator, {class_name: :User, inverse_of: :created_games}
  has_many :game_players, {class_name: :GameUser}
  has_many :players, {through: :game_players}
  has_many :rounds
  has_many :responses, {through: :rounds}
  
  # Validations
  validates_presence_of :creator_id, :creator
  validates_presence_of :current_state
  validates_numericality_of :current_state, {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 3}
  validates_numericality_of :num_players, {only_integer: true, greater_than_or_equal_to: 3, less_than_or_equal_to: 100}
  validates_numericality_of :num_rounds, {only_integer: true, greater_than_or_equal_to: :num_players, less_than_or_equal_to: 100}
  validates_numericality_of :timeout, {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 60}
  validates_numericality_of :current_round, {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: :num_rounds}

  # Callbacks
  before_validation :set_defaults, {on: :create}
  def set_defaults
    self.current_state = 1
    self.current_round = 0
  end
  protected :set_defaults

  # Scopes
  def self.created_by(user)
    where(creator: user)
  end
  def self.waiting_for_players
    where(current_state: 1)
  end
  def self.in_progress
    where(current_state: 2)
  end
  def self.complete
    where(current_state: 3)  
  end
  def self.active
    where(current_state: 1..2)
  end

  # Instance Methods - Predicates
  def waiting_for_players?
    current_state == 1
  end
  def in_progress?
    current_state == 2
  end
  def complete?
    current_state == 3
  end
  def active?
    waiting_for_players? || in_progress?
  end

  # Current round object
  def round
    rounds.find_by(round: current_round)
  end

  # Game players by points
  def game_players_by_points
    game_players.sort_by{|game_player| [-game_player.points, game_player.player.email.downcase]}
  end

  # Game Winners/Losers
  def winners
    winners = game_players.select{|game_player| game_player.result == 2}.map{|game_player| game_player.player}
    winners = game_players.select{|game_player| game_player.result == 1}.map{|game_player| game_player.player} if winners.count == 0
    winners
  end
  def losers
    game_players.select{|game_player| game_player.result == 0}.map{|game_player| player}
  end

  # Players left before game starts
  def num_players_missing
    num_players - game_players.count
  end

  # Add a player to the game
  def add_player(player)
    # Confirm user isn't already playing a game
    return errors.add(:base, 'Player is already playing a game') unless player.games.active.count == 0
    # Confirm the game is not full
    return errors.add(:base, 'Game is full') unless players.count < num_players
    # Add player
    game_players.create(player: player)
    start if players.count == num_players
  end

  # Start game
  def start
    # Randomly select cards and initial judge
    card_ids = Card.sample(num_rounds)
    first_judge_index = Random.new.rand(num_players)
    # Set up rounds
    num_rounds.times do |index|
      judge_index = ((first_judge_index + index) % num_players)
      rounds.create(round: (index + 1), card_id: card_ids[index], judge_id: player_ids[judge_index], points: num_players)
    end
    # Update game state
    next_round
    update_attributes(current_state: 2)
  end
  protected :start

  # Advance game to the next round or complete the game
  def next_round
    unless current_round == num_rounds
      update_attributes(current_round: current_round + 1)
      round.start_response_timer
    else
      max_points = game_players_by_points.first.points
      if max_points == 0
        game_players.each{|game_player| game_player.set_lose}
      else
        has_winner = game_players.select{|game_player| game_player.points == max_points}.count == 1
        if has_winner
          game_players_by_points.first.set_win
        else
          game_players.select{|game_player| game_player.points == max_points}.each{|game_player| game_player.set_tie}
        end
        game_players.reject{|game_player| game_player.points == max_points}.each{|game_player| game_player.set_lose}
      end
      update_attributes(current_state: 3)
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @game = Game.new
  end

  def create
    # Create new game
    safe_params = params.require(:game).permit(:num_players, :num_rounds, :timeout)
    @game = Game.create(safe_params.merge(creator: current_user))
    unless @game.errors.any?
      @game.add_player(current_user)
      return redirect_to(play_path, flash: {success: 'New game created successfully.'})
    else
      flash.now[:error] = @game.errors.full_messages.to_sentence
      return render :new
    end
  end

  # Join a game
  def join
    # Confirm game exists
    return redirect_to(play_path, {flash: {error: 'Unknown game.'}}) unless @game = Game.find_by(id: params[:game_id])
    # Attempt to add player to game
    @game.add_player(current_user)
    return @game.errors.any? ? redirect_to(play_path, {flash: {error: @game.errors.full_messages.to_sentence}}) : redirect_to(game_path(@game))
  end

  # Show a game
  def show
    # Confirm game exists
    return redirect_to(play_path, {flash: {error: 'Unknown game.'}}) unless @game = Game.find_by(id: params[:id])
    # Confirm user is playing game or game is complete
    return redirect_to(play_path, {flash: {error: 'You are not playing that game.'}}) unless @game.players.include?(current_user) || @game.complete?
    @round = @game.round
  end

  # Respond action
  def respond
    # Confirm game exists
    return redirect_to(play_path, {flash: {error: 'Unknown game.'}}) unless @game = Game.find_by(id: params[:game_id])
    # Confirm game is in progress and round is accepting responses
    return redirect_to(game_path(@game), {flash: {error: 'Game is not in progress'}}) unless @game.in_progress?
    @round = @game.round
    return redirect_to(game_path(@game), {flash: {error: 'Round is not accepting responses'}}) unless @round.accepting_responses?
    # Save response
    safe_params = params.require(:response).permit(:response)
    response = @round.save_response(safe_params.merge(player: current_user))
    # Render/Redirect
    if response.errors.any?
      flash.now[:error] = response.errors.full_messages.to_sentence
      return render :show
    else
      return redirect_to(game_path(@game))
    end
  end

  # Score action
  def score
    # Confirm game exists
    return redirect_to(play_path, {flash: {error: 'Unknown game.'}}) unless @game = Game.find_by(id: params[:game_id])
    # Confirm game is in progress, round is accepting scores, and current_user is the judge for round
    return redirect_to(game_path(@game), {flash: {error: 'Game is not in progress'}}) unless @game.in_progress?
    @round = @game.round
    return redirect_to(game_path(@game), {flash: {error: 'Round is not accepting scores'}}) unless @round.accepting_scores?
    return redirect_to(game_path(@game), {flash: {error: 'You are not the judge for this round'}}) unless @round.judge == current_user
    # Save scores
    safe_params = params.require(:round).permit(responses_attributes: [:id, :points])
    @round.save_scores(safe_params)
    # Render/Redirect
    if @round.errors.any?
      flash.now[:error] = @round.errors.full_messages.to_sentence
      return render :show
    else
      return redirect_to(game_path(@game))
    end
  end

end

app/views/games/_details.html.haml
- @game.rounds.each do |round|
  %h4= "Round #{round.round} - #{round.card.phrase}"
  %table.table.table-bordered.table-condensed
    %tr
      %th.span2 Player
      %th.span4 Response
      %th.span1 Points
    - round.responses_sorted_by_points_and_player.each do |response|
      %tr
        %td.span2= response.player.email
        %td.span4= response.response
        %td.span1= response.points

app/views/games/_info.html.haml
%h4 Dashboard
- if @game.waiting_for_players? || @game.complete?
  %div= "Rounds: #{@game.num_rounds}"
  %div= "Players: #{@game.num_players}"
- if @game.in_progress?
  %div= "Round: #{@round.round} of #{@game.num_rounds}"
  %div= "Judge: #{@round.judge.email}"
- if @game.complete?
  %div= "#{'Winner'.pluralize(@game.winners.count)}: #{@game.winners.map{|winner| winner.email}.to_sentence}"

app/views/games/_response_form.html.haml
= form_for(@round.responses.new, {url: game_respond_path(@game), method: :post, html: {class: 'form-horizontal'}}) do |form|
  %div.control-group
    = form.label(:response, {class: 'control-label'})
    %div.controls= form.text_field(:response)
  %div.control-group
    %div.controls= form.submit('Submit Response', {class: 'btn'})

app/views/games/_score_form.html.haml
= form_for(@round, {url: game_score_path(@game), method: :post, html: {class: 'form-horizontal'}}) do |round_form|
  %div.cntrol-group
    %div.controls
      %h5= "Award #{@round.points} total points."
  = round_form.fields_for(:responses, @round.responses_sorted_by_response) do |response_fields|
    %div.control-group
      %label.control-label= response_fields.object.response
      %div.controls= response_fields.text_field(:points)
  %div.control-group
    %div.controls= round_form.submit('Submit Points', {class: 'btn'})

app/views/games/_scoreboard.haml
%h4 Scoreboard
- @game.game_players_by_points.each do |game_player|
  %div= "#{game_player.player.email}: #{game_player.points}"

app/views/games/new.html.haml
%h4 New Game
= form_for(@game, {html: {class: 'form-horizontal'}}) do |f|
  %div.control-group
    = f.label(:num_players, {class: 'control-label'})
    %div.controls= f.text_field(:num_players, {placeholder: '3 - 100'})
  %div.control-group
    = f.label(:num_rounds, {class: 'control-label'})
    %div.controls= f.text_field(:num_rounds, {placeholder: '# of Players - 100'})
  %div.control-group
    = f.label(:timeout, {class: 'control-label'})
    %div.controls= f.text_field(:timeout, {placeholder: 'minutes'})
  %div.control-group
    %div.controls= f.submit({class: 'btn'})

app/views/games/show.html.haml
%div.row
  %div.span8
    - if @game.waiting_for_players?
      %div.waiting
        %h4= "Waiting for #{@game.num_players_missing} #{'player'.pluralize(@game.num_players_missing)} to join the game."
    - elsif @game.in_progress?
      %h3.phrase= "#{@round.card.phrase}..."
      - if @round.accepting_responses?
        - if @round.judge == current_user || @round.player_responded?(current_user)
          %div.waiting
            %h4= "Waiting for #{@round.num_responses_missing} #{'player'.pluralize(@round.num_responses_missing)} to respond."
        - else
          %div.response= render('response_form')
      - elsif @round.accepting_scores?
        - if @round.judge == current_user
          %div.score= render('score_form')
        - else
          %div.waiting
            %h4= "Waiting for #{@round.judge.email} to award points."
            %ul
              - @round.responses_sorted_by_response.each do |response|
                %li= response.response
      - else
        %div.waiting
    - elsif @game.complete?
      %div.details= render('details')
  %div.span4
    %div.info= render('info')
    - unless @game.waiting_for_players?
      %div.scoreboard= render('scoreboard')