config/routes.rb
ThingsToApples::Application.routes.draw do
  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: [:new, :create],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration
  end
  
  unauthenticated do
    root to: 'home#index'
  end
  get 'play' => 'home#play'
  get 'instructions' => 'home#instructions'
  get 'leaders' => 'home#leaders'
  get 'archives' => 'home#archives'

  authenticated :user do
    root to: 'home#play', as: :auth_root
  end

  resources :games, only: [:new, :create, :show] do
    post :join
    post :respond
    post :score
  end

  

end

app/views/layouts/_messages.html.haml
- flash.each do |type, msg|
  %div{class: "alert alert-#{type}"}
    %a.close{data: {dismiss: 'alert'}} &times;
    - if msg.is_a?(Array)
      %ul{id: "flash_#{type}"}
      - msg.each do |m|
        %li= m
    - else
      %span= msg

app/views/layouts/_navigation.html.haml
%div.navbar
  %div.navbar-inner
    = link_to('Things to Apples', play_path, {class: 'brand'})
    %ul.nav
      - if user_signed_in?
        %li= link_to('Play', play_path)
        %li.divider-vertical
        %li= link_to('Leaderboard', leaders_path)
        %li.divider-vertical
        %li= link_to('Game Archive', archives_path)
        %li.divider-vertical
      %li= link_to('Instructions', instructions_path)
    %ul.nav.pull-right
      - if user_signed_in?
        %li= link_to("Logout: #{current_user.email}", destroy_user_session_path, method: 'delete')
      - else
        %li= link_to('Login', new_user_session_path)
        %li.divider-vertical
        %li= link_to('Sign Up', new_user_registration_path)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Things To Apples</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="container" class="container">
      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>
      <footer>
      </footer>
    </div> <!--! end of #container -->
  </body>
</html>